name: Depoly

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Depoly
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Output to HTML
        uses: netwerk-digitaal-erfgoed/bikeshed-action@v1

      - name: Publish HTML to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET }}
