name: Build
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    # Note: `python` will also be this version, which various scripts depend on.
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # Note: `make deploy` will do a deploy dry run on PRs.
    - run: make deploy
      env:
        SERVER: ${{ secrets.SERVER_IP  }}
        SERVER_PUBLIC_KEY: ${{ secrets.SERVER_KEY}}
        SERVER_DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
        
    - name: "GitHub Push"
      if: ${{ GITHUB_EVENT_NAME == 'push' }}
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{secrets.SECRET}}
        repository: JunLiangWangX/DOM-Standard
        branch: deploy
        directory: DOM-Standard
