name: Depoly

on:
  push:
    branches:
      - main
      
jobs:
  main:
    name: Build and Depoly
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: dom.bs
