name: Depoly

on:
  push:
    branches: [main]
jobs:
  main:
    name: Deploy to GitHub pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BUILD_OVERRIDE: |
             Text-Macro: 'COMMIT-SHA LOCAL COPY'
          GH_PAGES_BRANCH: depoly
          TOOLCHAIN: bikeshed
          SOURCE: dom.bs
          DESTINATION: index.html
          GH_PAGES_TOKEN: ${{ secrets.SECRET }}
